# Graph Database Configuration for FAO Data
version: "1.0"

nodes:
  - table: area_codes
    label: AreaCode
      
  - table: reporter_country_codes
    label: ReporterCountryCode
      
  - table: partner_country_codes
    label: PartnerCountryCode
      
  - table: item_codes
    label: ItemCode

relationships:
  
  production_crops_livestock:
    - type: PRODUCES
      source:
        table: area_codes
        node_label: AreaCode
      target:
        table: item_codes
        node_label: ItemCode
      filters:
        - field: element_code
          join: true
          values_in: ["'5320'", "'5321'", "'5510'", "'5513'"]
          description: "Production quantities"
        - field: flag
          join: true
          values_in: ["'A'", "'X'", "'E'"]
          description: "official and estimated data"
        - field: year
          min_value: 2020
          description: "only data since 2020"
      exclude_properties:
        - months_code
        - year_code

  emissions_agriculture_energy:
    - type: EMITS
      source:
        table: area_codes
        node_label: AreaCode
      target:
        table: item_codes
        node_label: ItemCode
      filters:
        - field: element_code
          join: true
          values_in: ["'7225'", "'7230'", "'7273'"]  # Emissions from agriculture, energy, etc.
          description: "Emissions CH4, N2O, CO2 from agriculture and energy"
        - field: flag
          join: true
          values_in: ["'A'", "'X'", "'E'"]
          description: "official and estimated data"
        - field: year
          min_value: 2020
          description: "only data since 2020"
      exclude_properties:
        - months_code
        - year_code
  
    - type: USES
      source:
        table: area_codes
        node_label: AreaCode
      target:
        table: item_codes
        node_label: ItemCode
      filters:
        - field: element_code
          join: true
          value: "'72184'"  # Energy Use
          description: "Energy Use"
        - field: flag
          join: true
          values_in: ["'A'", "'X'", "'E'"]
          description: "official and estimated data"
        - field: year
          min_value: 2020
          description: "only data since 2020"
      exclude_properties:
        - months_code
        - year_code


  trade_detailed_trade_matrix:
    # Split into multiple relationship types for clarity
    - type: EXPORTS
      source:
        table: reporter_country_codes
        node_label: ReporterCountryCode
      target:
        table: item_codes  # Now targeting items!
        node_label: ItemCode
      filters:
        - field: element_code
          join: true
          values_in: ["'5910'", "'5922'"]  # Export Quantity/Value only
          description: "Export flows"
        - field: flag
          join: true
          value: "'A'"
          description: "official data"
        - field: year
          min_value: 2020
      exclude_properties:
        - months_code
        - year_code
        
    - type: IMPORTS
      source:
        table: item_codes
        node_label: ItemCode
      target:
        table: partner_country_codes
        node_label: PartnerCountryCode
      filters:
        - field: element_code
          join: true
          values_in: ["'5610'", "'5622'"]  # Import Quantity/Value
          description: "Import flows"
        - field: flag
          join: true
          value: "'A'"
        - field: year
          min_value: 2020
      exclude_properties:
        - months_code
        - year_code


  food_balance_sheets:
    - type: PRODUCES
      source:
        table: area_codes
        node_label: AreaCode
      target:
        table: item_codes
        node_label: ItemCode
      filters:
        - field: element_code
          join: true
          values_in: ["'5511'", "'5301'"]  # Production, Domestic supply
          description: "Production quantities"
        - field: flag
          join: true
          values_in: ["'A'", "'X'", "'E'"]
          description: "official and estimated data"
        - field: year
          min_value: 2020
          description: "only data since 2020"
      exclude_properties:
        - months_code
        - year_code
        
    - type: TRADES
      source:
        table: area_codes
        node_label: AreaCode
      target:
        table: item_codes
        node_label: ItemCode
      filters:
        - field: element_code
          join: true
          values_in: ["'5611'", "'5911'"]  # Import/Export Quantity
          description: "Trade quantities"
        - field: flag
          join: true
          values_in: ["'A'", "'X'", "'E'"]
          description: "official and estimated data"
        - field: year
          min_value: 2020
          description: "only data since 2020"
      exclude_properties:
        - months_code
        - year_code
        
    - type: USES
      source:
        table: area_codes
        node_label: AreaCode
      target:
        table: item_codes
        node_label: ItemCode
      filters:
        - field: element_code
          join: true
          values_in: ["'5142'", "'645'", "'664'", "'674'"]  # Food consumption
          description: "Food consumption"
        - field: flag
          join: true
          values_in: ["'A'", "'X'", "'E'"]
          description: "official and estimated data"
        - field: year
          min_value: 2020
          description: "only data since 2020"
      exclude_properties:
        - months_code
        - year_code
        
  food_security_data:
    - type: EXPERIENCES
      source:
        table: area_codes
        node_label: AreaCode
      target:
        table: item_codes
        node_label: ItemCode
      filters:
        - field: element_code
          join: true
          values_in: ["'61212'", "'61322'", "'61211'", "'61321'"]
          description: "Food insecurity experience scale"
        - field: flag
          join: true
          values_in: ["'A'", "'X'", "'E'"]
          description: "official and estimated data"
      exclude_properties:
        - months_code
        - year_code

    - type: MEASURES
      source:
        table: area_codes
        node_label: AreaCode
      target:
        table: item_codes
        node_label: ItemCode
      filters:
        - field: element_code
          join: true
          values_in: ["'6123'", "'6128'","'6126'","'6125'","'6132'","'6121'","'6173'","'6124'"]
          description: "Prevalence indicators"
        - field: flag
          join: true
          values_in: ["'A'", "'X'", "'E'"]
          description: "official and estimated data"
      exclude_properties:
        - months_code
        - year_code
        
  prices:
    - type: HAS_PRICE
      source:
        table: area_codes
        node_label: AreaCode
      target:
        table: item_codes
        node_label: ItemCode
      filters:
        - field: element_code
          join: true
          values_in: ["'5530'", "'5532'"]  # Producer prices
          description: "Producer price LCU/USD"
        - field: flag
          join: true
          values_in: ["'A'", "'X'"]
          description: "official and estimated data"
        - field: year
          min_value: 2020
          description: "only data since 2020"
      exclude_properties:
        - months_code
        - year_code

# Global settings
settings:
  batch_size: 10000
  create_indexes: true
  verify_after_migration: true
  replace_columns:
    description: "flag_description"
  indexes:
    element_code: "element_code"
    value: "value"
    flag: "flag"
    _self_: "_self_"
      
  
# Property group definitions (for documentation)
property_groups:
  time_columns: "year, months, date, period - whatever exists"
  value_columns: "value, quantity, amount, price - whatever exists"
  identifiers: "Foreign key IDs like element_code_id"
  metadata: "unit, flag, source - standard metadata"
  notes: "note, notes, comment - text fields"
  months: "months, months_code - monthly data"
  all: "Include all columns from the table"