"""add aquastat

Revision ID: 1eca3c87538f
Revises: 71b73d4e96a3
Create Date: 2025-06-08 11:44:30.186782

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1eca3c87538f'
down_revision: Union[str, None] = '71b73d4e96a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aquastat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('area_code_id', sa.Integer(), nullable=True),
    sa.Column('element_code_id', sa.Integer(), nullable=True),
    sa.Column('flag_id', sa.Integer(), nullable=True),
    sa.Column('unit', sa.String(length=50), nullable=True),
    sa.Column('year', sa.SmallInteger(), nullable=False),
    sa.Column('year_code', sa.String(length=4), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['area_code_id'], ['area_codes.id'], ),
    sa.ForeignKeyConstraint(['element_code_id'], ['elements.id'], ),
    sa.ForeignKeyConstraint(['flag_id'], ['flags.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_aquastat_area_code_id'), 'aquastat', ['area_code_id'], unique=False)
    op.create_index(op.f('ix_aquastat_element_code_id'), 'aquastat', ['element_code_id'], unique=False)
    op.create_index(op.f('ix_aquastat_flag_id'), 'aquastat', ['flag_id'], unique=False)
    op.create_index(op.f('ix_aquastat_year'), 'aquastat', ['year'], unique=False)
    op.alter_column('area_codes', 'area_code_m49',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('area_codes', 'area_code_m49',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_index(op.f('ix_aquastat_year'), table_name='aquastat')
    op.drop_index(op.f('ix_aquastat_flag_id'), table_name='aquastat')
    op.drop_index(op.f('ix_aquastat_element_code_id'), table_name='aquastat')
    op.drop_index(op.f('ix_aquastat_area_code_id'), table_name='aquastat')
    op.drop_table('aquastat')
    # ### end Alembic commands ###
