"""fix_population_age_groups_duplicate_columns

Revision ID: 71b73d4e96a3
Revises: ecb47b5d8a42
Create Date: 2025-06-08 09:50:42.202193

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '71b73d4e96a3'
down_revision: Union[str, None] = 'ecb47b5d8a42'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('population_age_groups', 'population_age_group_code',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('population_age_groups', 'population_age_group',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('population_age_groups', 'population_age_group_1')
    op.drop_column('population_age_groups', 'population_age_group_code_1')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('population_age_groups', sa.Column('population_age_group_code_1', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('population_age_groups', sa.Column('population_age_group_1', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.alter_column('population_age_groups', 'population_age_group',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('population_age_groups', 'population_age_group_code',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
