"""add year indexes with proper types

Revision ID: ecb47b5d8a42
Revises: 
Create Date: 2025-06-08 09:00:16.251999

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ecb47b5d8a42'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_area_codes_area_code'), table_name='area_codes')
    op.alter_column('asti_expenditures', 'year',
               existing_type=sa.INTEGER(),
               type_=sa.SmallInteger(),
               existing_nullable=False)
    op.create_index(op.f('ix_asti_expenditures_year'), 'asti_expenditures', ['year'], unique=False)
    op.alter_column('asti_researchers', 'year',
               existing_type=sa.INTEGER(),
               type_=sa.SmallInteger(),
               existing_nullable=False)
    op.create_index(op.f('ix_asti_researchers_year'), 'asti_researchers', ['year'], unique=False)
    op.alter_column('climate_change_emissions_indicators', 'year',
               existing_type=sa.INTEGER(),
               type_=sa.SmallInteger(),
               existing_nullable=False)
    op.create_index(op.f('ix_climate_change_emissions_indicators_year'), 'climate_change_emissions_indicators', ['year'], unique=False)
    op.alter_column('commodity_balances_non_food', 'year',
               existing_type=sa.INTEGER(),
               type_=sa.SmallInteger(),
               existing_nullable=False)
    op.create_index(op.f('ix_commodity_balances_non_food_year'), 'commodity_balances_non_food', ['year'], unique=False)
    op.alter_column('commodity_balances_non_food_2010', 'year',
               existing_type=sa.INTEGER(),
               type_=sa.SmallInteger(),
               existing_nullable=False)
    op.create_index(op.f('ix_commodity_balances_non_food_2010_year'), 'commodity_balances_non_food_2010', ['year'], unique=False)
    op.alter_column('commodity_balances_non_food_2013_old_methodology', 'year',
               existing_type=sa.INTEGER(),
               type_=sa.SmallInteger(),
               existing_nullable=False)
    op.create_index(op.f('ix_commodity_balances_non_food_2013_old_methodology_year'), 'commodity_balances_non_food_2013_old_methodology', ['year'], unique=False)
    op.alter_column('consumer_price_indices', 'year',
               existing_type=sa.INTEGER(),
               type_=sa.SmallInteger(),
               existing_nullable=False)
    op.create_index(op.f('ix_consumer_price_indices_year'), 'consumer_price_indices', ['year'], unique=False)
    op.alter_column('cost_affordability_healthy_diet_co_ahd', 'year',
               existing_type=sa.INTEGER(),
               type_=sa.SmallInteger(),
               existing_nullable=False)
    op.create_index(op.f('ix_cost_affordability_healthy_diet_co_ahd_year'), 'cost_affordability_healthy_diet_co_ahd', ['year'], unique=False)
    op.drop_index(op.f('ix_currencies_iso_currency_code'), table_name='currencies')
    op.alter_column('deflators', 'year',
               existing_type=sa.INTEGER(),
               type_=sa.SmallInteger(),
               existing_nullable=False)
    op.create_index(op.f('ix_deflators_year'), 'deflators', ['year'], unique=False)
    op.alter_column('development_assistance_to_agriculture', 'year',
               existing_type=sa.INTEGER(),
               type_=sa.SmallInteger(),
               existing_nullable=False)
    op.create_index(op.f('ix_development_assistance_to_agriculture_year'), 'development_assistance_to_agriculture', ['year'], unique=False)
    op.drop_index(op.f('ix_donors_donor_code'), table_name='donors')
    op.drop_index(op.f('ix_elements_element_code'), table_name='elements')
    op.alter_column('emissions_agriculture_energy', 'year',
               existing_type=sa.INTEGER(),
               type_=sa.SmallInteger(),
               existing_nullable=False)
    op.create_index(op.f('ix_emissions_agriculture_energy_year'), 'emissions_agriculture_energy', ['year'], unique=False)
    op.alter_column('emissions_crops', 'year',
               existing_type=sa.INTEGER(),
               type_=sa.SmallInteger(),
               existing_nullable=False)
    op.create_index(op.f('ix_emissions_crops_year'), 'emissions_crops', ['year'], unique=False)
    op.alter_column('emissions_drained_organic_soils', 'year',
               existing_type=sa.INTEGER(),
               type_=sa.SmallInteger(),
               existing_nullable=False)
    op.create_index(op.f('ix_emissions_drained_organic_soils_year'), 'emissions_drained_organic_soils', ['year'], unique=False)
    op.alter_column('emissions_land_use_fires', 'year',
               existing_type=sa.INTEGER(),
               type_=sa.SmallInteger(),
               existing_nullable=False)
    op.create_index(op.f('ix_emissions_land_use_fires_year'), 'emissions_land_use_fires', ['year'], unique=False)
    op.alter_column('emissions_land_use_forests', 'year',
               existing_type=sa.INTEGER(),
               type_=sa.SmallInteger(),
               existing_nullable=False)
    op.create_index(op.f('ix_emissions_land_use_forests_year'), 'emissions_land_use_forests', ['year'], unique=False)
    op.alter_column('emissions_livestock', 'year',
               existing_type=sa.INTEGER(),
               type_=sa.SmallInteger(),
               existing_nullable=False)
    op.create_index(op.f('ix_emissions_livestock_year'), 'emissions_livestock', ['year'], unique=False)
    op.alter_column('emissions_pre_post_production', 'year',
               existing_type=sa.INTEGER(),
               type_=sa.SmallInteger(),
               existing_nullable=False)
    op.alter_column('emissions_pre_post_production', 'value',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.create_index(op.f('ix_emissions_pre_post_production_year'), 'emissions_pre_post_production', ['year'], unique=False)
    op.alter_column('emissions_totals', 'year',
               existing_type=sa.INTEGER(),
               type_=sa.SmallInteger(),
               existing_nullable=False)
    op.create_index(op.f('ix_emissions_totals_year'), 'emissions_totals', ['year'], unique=False)
    op.alter_column('employment_indicators_agriculture', 'year',
               existing_type=sa.INTEGER(),
               type_=sa.SmallInteger(),
               existing_nullable=False)
    op.create_index(op.f('ix_employment_indicators_agriculture_year'), 'employment_indicators_agriculture', ['year'], unique=False)
    op.alter_column('employment_indicators_rural', 'year',
               existing_type=sa.INTEGER(),
               type_=sa.SmallInteger(),
               existing_nullable=False)
    op.create_index(op.f('ix_employment_indicators_rural_year'), 'employment_indicators_rural', ['year'], unique=False)
    op.alter_column('environment_bioenergy', 'year',
               existing_type=sa.INTEGER(),
               type_=sa.SmallInteger(),
               existing_nullable=False)
    op.create_index(op.f('ix_environment_bioenergy_year'), 'environment_bioenergy', ['year'], unique=False)
    op.alter_column('environment_cropland_nutrient_budget', 'year',
               existing_type=sa.INTEGER(),
               type_=sa.SmallInteger(),
               existing_nullable=False)
    op.create_index(op.f('ix_environment_cropland_nutrient_budget_year'), 'environment_cropland_nutrient_budget', ['year'], unique=False)
    op.alter_column('environment_emissions_by_sector', 'year',
               existing_type=sa.INTEGER(),
               type_=sa.SmallInteger(),
               existing_nullable=False)
    op.create_index(op.f('ix_environment_emissions_by_sector_year'), 'environment_emissions_by_sector', ['year'], unique=False)
    op.alter_column('environment_emissions_intensities', 'year',
               existing_type=sa.INTEGER(),
               type_=sa.SmallInteger(),
               existing_nullable=False)
    op.create_index(op.f('ix_environment_emissions_intensities_year'), 'environment_emissions_intensities', ['year'], unique=False)
    op.alter_column('environment_food_waste_disposal', 'year',
               existing_type=sa.INTEGER(),
               type_=sa.SmallInteger(),
               existing_nullable=False)
    op.alter_column('environment_food_waste_disposal', 'value',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.create_index(op.f('ix_environment_food_waste_disposal_year'), 'environment_food_waste_disposal', ['year'], unique=False)
    op.alter_column('environment_land_cover', 'year',
               existing_type=sa.INTEGER(),
               type_=sa.SmallInteger(),
               existing_nullable=False)
    op.create_index(op.f('ix_environment_land_cover_year'), 'environment_land_cover', ['year'], unique=False)
    op.alter_column('environment_land_use', 'year',
               existing_type=sa.INTEGER(),
               type_=sa.SmallInteger(),
               existing_nullable=False)
    op.create_index(op.f('ix_environment_land_use_year'), 'environment_land_use', ['year'], unique=False)
    op.alter_column('environment_livestock_manure', 'year',
               existing_type=sa.INTEGER(),
               type_=sa.SmallInteger(),
               existing_nullable=False)
    op.create_index(op.f('ix_environment_livestock_manure_year'), 'environment_livestock_manure', ['year'], unique=False)
    op.alter_column('environment_livestock_patterns', 'year',
               existing_type=sa.INTEGER(),
               type_=sa.SmallInteger(),
               existing_nullable=False)
    op.create_index(op.f('ix_environment_livestock_patterns_year'), 'environment_livestock_patterns', ['year'], unique=False)
    op.alter_column('environment_pesticides', 'year',
               existing_type=sa.INTEGER(),
               type_=sa.SmallInteger(),
               existing_nullable=False)
    op.create_index(op.f('ix_environment_pesticides_year'), 'environment_pesticides', ['year'], unique=False)
    op.alter_column('environment_soil_nutrient_budget', 'year',
               existing_type=sa.INTEGER(),
               type_=sa.SmallInteger(),
               existing_nullable=False)
    op.create_index(op.f('ix_environment_soil_nutrient_budget_year'), 'environment_soil_nutrient_budget', ['year'], unique=False)
    op.alter_column('environment_temperature_change', 'year',
               existing_type=sa.INTEGER(),
               type_=sa.SmallInteger(),
               existing_nullable=False)
    op.create_index(op.f('ix_environment_temperature_change_year'), 'environment_temperature_change', ['year'], unique=False)
    op.alter_column('exchange_rate', 'year',
               existing_type=sa.INTEGER(),
               type_=sa.SmallInteger(),
               existing_nullable=False)
    op.create_index(op.f('ix_exchange_rate_year'), 'exchange_rate', ['year'], unique=False)
    op.alter_column('fertilizers_detailed_trade_matrix', 'year',
               existing_type=sa.INTEGER(),
               type_=sa.SmallInteger(),
               existing_nullable=False)
    op.create_index(op.f('ix_fertilizers_detailed_trade_matrix_year'), 'fertilizers_detailed_trade_matrix', ['year'], unique=False)
    op.alter_column('food_aid_shipments_wfp', 'year',
               existing_type=sa.INTEGER(),
               type_=sa.SmallInteger(),
               existing_nullable=False)
    op.create_index(op.f('ix_food_aid_shipments_wfp_year'), 'food_aid_shipments_wfp', ['year'], unique=False)
    op.alter_column('food_balance_sheets', 'year',
               existing_type=sa.INTEGER(),
               type_=sa.SmallInteger(),
               existing_nullable=False)
    op.create_index(op.f('ix_food_balance_sheets_year'), 'food_balance_sheets', ['year'], unique=False)
    op.alter_column('food_balance_sheets_historic', 'year',
               existing_type=sa.INTEGER(),
               type_=sa.SmallInteger(),
               existing_nullable=False)
    op.create_index(op.f('ix_food_balance_sheets_historic_year'), 'food_balance_sheets_historic', ['year'], unique=False)
    op.drop_index(op.f('ix_food_groups_food_group_code'), table_name='food_groups')
    op.create_index(op.f('ix_food_security_data_year'), 'food_security_data', ['year'], unique=False)
    op.alter_column('forestry', 'year',
               existing_type=sa.INTEGER(),
               type_=sa.SmallInteger(),
               existing_nullable=False)
    op.create_index(op.f('ix_forestry_year'), 'forestry', ['year'], unique=False)
    op.alter_column('forestry_pulp_paper_survey', 'year',
               existing_type=sa.INTEGER(),
               type_=sa.SmallInteger(),
               existing_nullable=False)
    op.create_index(op.f('ix_forestry_pulp_paper_survey_year'), 'forestry_pulp_paper_survey', ['year'], unique=False)
    op.alter_column('forestry_trade_flows', 'year',
               existing_type=sa.INTEGER(),
               type_=sa.SmallInteger(),
               existing_nullable=False)
    op.create_index(op.f('ix_forestry_trade_flows_year'), 'forestry_trade_flows', ['year'], unique=False)
    op.drop_index(op.f('ix_geographic_levels_geographic_level_code'), table_name='geographic_levels')
    op.drop_index(op.f('ix_indicators_indicator_code'), table_name='indicators')
    op.alter_column('indicators_from_household_surveys', 'value',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('individual_quantitative_dietary_data_food_and_diet', 'value',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('inputs_fertilizers_archive', 'year',
               existing_type=sa.INTEGER(),
               type_=sa.SmallInteger(),
               existing_nullable=False)
    op.create_index(op.f('ix_inputs_fertilizers_archive_year'), 'inputs_fertilizers_archive', ['year'], unique=False)
    op.alter_column('inputs_fertilizers_nutrient', 'year',
               existing_type=sa.INTEGER(),
               type_=sa.SmallInteger(),
               existing_nullable=False)
    op.create_index(op.f('ix_inputs_fertilizers_nutrient_year'), 'inputs_fertilizers_nutrient', ['year'], unique=False)
    op.alter_column('inputs_fertilizers_product', 'year',
               existing_type=sa.INTEGER(),
               type_=sa.SmallInteger(),
               existing_nullable=False)
    op.create_index(op.f('ix_inputs_fertilizers_product_year'), 'inputs_fertilizers_product', ['year'], unique=False)
    op.alter_column('inputs_land_use', 'year',
               existing_type=sa.INTEGER(),
               type_=sa.SmallInteger(),
               existing_nullable=False)
    op.create_index(op.f('ix_inputs_land_use_year'), 'inputs_land_use', ['year'], unique=False)
    op.alter_column('inputs_pesticides_trade', 'year',
               existing_type=sa.INTEGER(),
               type_=sa.SmallInteger(),
               existing_nullable=False)
    op.create_index(op.f('ix_inputs_pesticides_trade_year'), 'inputs_pesticides_trade', ['year'], unique=False)
    op.alter_column('inputs_pesticides_use', 'year',
               existing_type=sa.INTEGER(),
               type_=sa.SmallInteger(),
               existing_nullable=False)
    op.create_index(op.f('ix_inputs_pesticides_use_year'), 'inputs_pesticides_use', ['year'], unique=False)
    op.alter_column('investment_capital_stock', 'year',
               existing_type=sa.INTEGER(),
               type_=sa.SmallInteger(),
               existing_nullable=False)
    op.create_index(op.f('ix_investment_capital_stock_year'), 'investment_capital_stock', ['year'], unique=False)
    op.alter_column('investment_country_investment_statistics_profile', 'year',
               existing_type=sa.INTEGER(),
               type_=sa.SmallInteger(),
               existing_nullable=False)
    op.create_index(op.f('ix_investment_country_investment_statistics_profile_year'), 'investment_country_investment_statistics_profile', ['year'], unique=False)
    op.alter_column('investment_credit_agriculture', 'year',
               existing_type=sa.INTEGER(),
               type_=sa.SmallInteger(),
               existing_nullable=False)
    op.create_index(op.f('ix_investment_credit_agriculture_year'), 'investment_credit_agriculture', ['year'], unique=False)
    op.alter_column('investment_foreign_direct_investment', 'year',
               existing_type=sa.INTEGER(),
               type_=sa.SmallInteger(),
               existing_nullable=False)
    op.alter_column('investment_foreign_direct_investment', 'value',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.create_index(op.f('ix_investment_foreign_direct_investment_year'), 'investment_foreign_direct_investment', ['year'], unique=False)
    op.alter_column('investment_government_expenditure', 'year',
               existing_type=sa.INTEGER(),
               type_=sa.SmallInteger(),
               existing_nullable=False)
    op.create_index(op.f('ix_investment_government_expenditure_year'), 'investment_government_expenditure', ['year'], unique=False)
    op.alter_column('investment_machinery', 'year',
               existing_type=sa.INTEGER(),
               type_=sa.SmallInteger(),
               existing_nullable=False)
    op.create_index(op.f('ix_investment_machinery_year'), 'investment_machinery', ['year'], unique=False)
    op.alter_column('investment_machinery_archive', 'year',
               existing_type=sa.INTEGER(),
               type_=sa.SmallInteger(),
               existing_nullable=False)
    op.create_index(op.f('ix_investment_machinery_archive_year'), 'investment_machinery_archive', ['year'], unique=False)
    op.drop_index(op.f('ix_item_codes_item_code'), table_name='item_codes')
    op.alter_column('macro_statistics_key_indicators', 'year',
               existing_type=sa.INTEGER(),
               type_=sa.SmallInteger(),
               existing_nullable=False)
    op.create_index(op.f('ix_macro_statistics_key_indicators_year'), 'macro_statistics_key_indicators', ['year'], unique=False)
    op.alter_column('population', 'year',
               existing_type=sa.INTEGER(),
               type_=sa.SmallInteger(),
               existing_nullable=False)
    op.create_index(op.f('ix_population_year'), 'population', ['year'], unique=False)
    op.alter_column('population_age_groups', 'population_age_group_code',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_index(op.f('ix_population_age_groups_population_age_group_code'), table_name='population_age_groups')
    op.alter_column('prices', 'year',
               existing_type=sa.INTEGER(),
               type_=sa.SmallInteger(),
               existing_nullable=False)
    op.create_index(op.f('ix_prices_year'), 'prices', ['year'], unique=False)
    op.alter_column('prices_archive', 'year',
               existing_type=sa.INTEGER(),
               type_=sa.SmallInteger(),
               existing_nullable=False)
    op.create_index(op.f('ix_prices_archive_year'), 'prices_archive', ['year'], unique=False)
    op.alter_column('production_crops_livestock', 'year',
               existing_type=sa.INTEGER(),
               type_=sa.SmallInteger(),
               existing_nullable=False)
    op.create_index(op.f('ix_production_crops_livestock_year'), 'production_crops_livestock', ['year'], unique=False)
    op.alter_column('production_indices', 'year',
               existing_type=sa.INTEGER(),
               type_=sa.SmallInteger(),
               existing_nullable=False)
    op.create_index(op.f('ix_production_indices_year'), 'production_indices', ['year'], unique=False)
    op.drop_index(op.f('ix_purposes_purpose_code'), table_name='purposes')
    op.drop_index(op.f('ix_releases_release_code'), table_name='releases')
    op.alter_column('sdg_bulk_downloads', 'year',
               existing_type=sa.INTEGER(),
               type_=sa.SmallInteger(),
               existing_nullable=False)
    op.create_index(op.f('ix_sdg_bulk_downloads_year'), 'sdg_bulk_downloads', ['year'], unique=False)
    op.drop_index(op.f('ix_sexs_sex_code'), table_name='sexs')
    op.drop_index(op.f('ix_sources_source_code'), table_name='sources')
    op.alter_column('sua_crops_livestock', 'year',
               existing_type=sa.INTEGER(),
               type_=sa.SmallInteger(),
               existing_nullable=False)
    op.create_index(op.f('ix_sua_crops_livestock_year'), 'sua_crops_livestock', ['year'], unique=False)
    op.alter_column('supply_utilization_accounts_food_and_diet', 'year',
               existing_type=sa.INTEGER(),
               type_=sa.SmallInteger(),
               existing_nullable=False)
    op.create_index(op.f('ix_supply_utilization_accounts_food_and_diet_year'), 'supply_utilization_accounts_food_and_diet', ['year'], unique=False)
    op.drop_index(op.f('ix_surveys_survey_code'), table_name='surveys')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_surveys_survey_code'), 'surveys', ['survey_code'], unique=False)
    op.drop_index(op.f('ix_supply_utilization_accounts_food_and_diet_year'), table_name='supply_utilization_accounts_food_and_diet')
    op.alter_column('supply_utilization_accounts_food_and_diet', 'year',
               existing_type=sa.SmallInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_index(op.f('ix_sua_crops_livestock_year'), table_name='sua_crops_livestock')
    op.alter_column('sua_crops_livestock', 'year',
               existing_type=sa.SmallInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.create_index(op.f('ix_sources_source_code'), 'sources', ['source_code'], unique=False)
    op.create_index(op.f('ix_sexs_sex_code'), 'sexs', ['sex_code'], unique=False)
    op.drop_index(op.f('ix_sdg_bulk_downloads_year'), table_name='sdg_bulk_downloads')
    op.alter_column('sdg_bulk_downloads', 'year',
               existing_type=sa.SmallInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.create_index(op.f('ix_releases_release_code'), 'releases', ['release_code'], unique=False)
    op.create_index(op.f('ix_purposes_purpose_code'), 'purposes', ['purpose_code'], unique=False)
    op.drop_index(op.f('ix_production_indices_year'), table_name='production_indices')
    op.alter_column('production_indices', 'year',
               existing_type=sa.SmallInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_index(op.f('ix_production_crops_livestock_year'), table_name='production_crops_livestock')
    op.alter_column('production_crops_livestock', 'year',
               existing_type=sa.SmallInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_index(op.f('ix_prices_archive_year'), table_name='prices_archive')
    op.alter_column('prices_archive', 'year',
               existing_type=sa.SmallInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_index(op.f('ix_prices_year'), table_name='prices')
    op.alter_column('prices', 'year',
               existing_type=sa.SmallInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.create_index(op.f('ix_population_age_groups_population_age_group_code'), 'population_age_groups', ['population_age_group_code'], unique=False)
    op.alter_column('population_age_groups', 'population_age_group_code',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_index(op.f('ix_population_year'), table_name='population')
    op.alter_column('population', 'year',
               existing_type=sa.SmallInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_index(op.f('ix_macro_statistics_key_indicators_year'), table_name='macro_statistics_key_indicators')
    op.alter_column('macro_statistics_key_indicators', 'year',
               existing_type=sa.SmallInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.create_index(op.f('ix_item_codes_item_code'), 'item_codes', ['item_code'], unique=False)
    op.drop_index(op.f('ix_investment_machinery_archive_year'), table_name='investment_machinery_archive')
    op.alter_column('investment_machinery_archive', 'year',
               existing_type=sa.SmallInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_index(op.f('ix_investment_machinery_year'), table_name='investment_machinery')
    op.alter_column('investment_machinery', 'year',
               existing_type=sa.SmallInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_index(op.f('ix_investment_government_expenditure_year'), table_name='investment_government_expenditure')
    op.alter_column('investment_government_expenditure', 'year',
               existing_type=sa.SmallInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_index(op.f('ix_investment_foreign_direct_investment_year'), table_name='investment_foreign_direct_investment')
    op.alter_column('investment_foreign_direct_investment', 'value',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('investment_foreign_direct_investment', 'year',
               existing_type=sa.SmallInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_index(op.f('ix_investment_credit_agriculture_year'), table_name='investment_credit_agriculture')
    op.alter_column('investment_credit_agriculture', 'year',
               existing_type=sa.SmallInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_index(op.f('ix_investment_country_investment_statistics_profile_year'), table_name='investment_country_investment_statistics_profile')
    op.alter_column('investment_country_investment_statistics_profile', 'year',
               existing_type=sa.SmallInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_index(op.f('ix_investment_capital_stock_year'), table_name='investment_capital_stock')
    op.alter_column('investment_capital_stock', 'year',
               existing_type=sa.SmallInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_index(op.f('ix_inputs_pesticides_use_year'), table_name='inputs_pesticides_use')
    op.alter_column('inputs_pesticides_use', 'year',
               existing_type=sa.SmallInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_index(op.f('ix_inputs_pesticides_trade_year'), table_name='inputs_pesticides_trade')
    op.alter_column('inputs_pesticides_trade', 'year',
               existing_type=sa.SmallInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_index(op.f('ix_inputs_land_use_year'), table_name='inputs_land_use')
    op.alter_column('inputs_land_use', 'year',
               existing_type=sa.SmallInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_index(op.f('ix_inputs_fertilizers_product_year'), table_name='inputs_fertilizers_product')
    op.alter_column('inputs_fertilizers_product', 'year',
               existing_type=sa.SmallInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_index(op.f('ix_inputs_fertilizers_nutrient_year'), table_name='inputs_fertilizers_nutrient')
    op.alter_column('inputs_fertilizers_nutrient', 'year',
               existing_type=sa.SmallInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_index(op.f('ix_inputs_fertilizers_archive_year'), table_name='inputs_fertilizers_archive')
    op.alter_column('inputs_fertilizers_archive', 'year',
               existing_type=sa.SmallInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('individual_quantitative_dietary_data_food_and_diet', 'value',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('indicators_from_household_surveys', 'value',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.create_index(op.f('ix_indicators_indicator_code'), 'indicators', ['indicator_code'], unique=False)
    op.create_index(op.f('ix_geographic_levels_geographic_level_code'), 'geographic_levels', ['geographic_level_code'], unique=False)
    op.drop_index(op.f('ix_forestry_trade_flows_year'), table_name='forestry_trade_flows')
    op.alter_column('forestry_trade_flows', 'year',
               existing_type=sa.SmallInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_index(op.f('ix_forestry_pulp_paper_survey_year'), table_name='forestry_pulp_paper_survey')
    op.alter_column('forestry_pulp_paper_survey', 'year',
               existing_type=sa.SmallInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_index(op.f('ix_forestry_year'), table_name='forestry')
    op.alter_column('forestry', 'year',
               existing_type=sa.SmallInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_index(op.f('ix_food_security_data_year'), table_name='food_security_data')
    op.create_index(op.f('ix_food_groups_food_group_code'), 'food_groups', ['food_group_code'], unique=False)
    op.drop_index(op.f('ix_food_balance_sheets_historic_year'), table_name='food_balance_sheets_historic')
    op.alter_column('food_balance_sheets_historic', 'year',
               existing_type=sa.SmallInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_index(op.f('ix_food_balance_sheets_year'), table_name='food_balance_sheets')
    op.alter_column('food_balance_sheets', 'year',
               existing_type=sa.SmallInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_index(op.f('ix_food_aid_shipments_wfp_year'), table_name='food_aid_shipments_wfp')
    op.alter_column('food_aid_shipments_wfp', 'year',
               existing_type=sa.SmallInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_index(op.f('ix_fertilizers_detailed_trade_matrix_year'), table_name='fertilizers_detailed_trade_matrix')
    op.alter_column('fertilizers_detailed_trade_matrix', 'year',
               existing_type=sa.SmallInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_index(op.f('ix_exchange_rate_year'), table_name='exchange_rate')
    op.alter_column('exchange_rate', 'year',
               existing_type=sa.SmallInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_index(op.f('ix_environment_temperature_change_year'), table_name='environment_temperature_change')
    op.alter_column('environment_temperature_change', 'year',
               existing_type=sa.SmallInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_index(op.f('ix_environment_soil_nutrient_budget_year'), table_name='environment_soil_nutrient_budget')
    op.alter_column('environment_soil_nutrient_budget', 'year',
               existing_type=sa.SmallInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_index(op.f('ix_environment_pesticides_year'), table_name='environment_pesticides')
    op.alter_column('environment_pesticides', 'year',
               existing_type=sa.SmallInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_index(op.f('ix_environment_livestock_patterns_year'), table_name='environment_livestock_patterns')
    op.alter_column('environment_livestock_patterns', 'year',
               existing_type=sa.SmallInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_index(op.f('ix_environment_livestock_manure_year'), table_name='environment_livestock_manure')
    op.alter_column('environment_livestock_manure', 'year',
               existing_type=sa.SmallInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_index(op.f('ix_environment_land_use_year'), table_name='environment_land_use')
    op.alter_column('environment_land_use', 'year',
               existing_type=sa.SmallInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_index(op.f('ix_environment_land_cover_year'), table_name='environment_land_cover')
    op.alter_column('environment_land_cover', 'year',
               existing_type=sa.SmallInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_index(op.f('ix_environment_food_waste_disposal_year'), table_name='environment_food_waste_disposal')
    op.alter_column('environment_food_waste_disposal', 'value',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('environment_food_waste_disposal', 'year',
               existing_type=sa.SmallInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_index(op.f('ix_environment_emissions_intensities_year'), table_name='environment_emissions_intensities')
    op.alter_column('environment_emissions_intensities', 'year',
               existing_type=sa.SmallInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_index(op.f('ix_environment_emissions_by_sector_year'), table_name='environment_emissions_by_sector')
    op.alter_column('environment_emissions_by_sector', 'year',
               existing_type=sa.SmallInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_index(op.f('ix_environment_cropland_nutrient_budget_year'), table_name='environment_cropland_nutrient_budget')
    op.alter_column('environment_cropland_nutrient_budget', 'year',
               existing_type=sa.SmallInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_index(op.f('ix_environment_bioenergy_year'), table_name='environment_bioenergy')
    op.alter_column('environment_bioenergy', 'year',
               existing_type=sa.SmallInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_index(op.f('ix_employment_indicators_rural_year'), table_name='employment_indicators_rural')
    op.alter_column('employment_indicators_rural', 'year',
               existing_type=sa.SmallInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_index(op.f('ix_employment_indicators_agriculture_year'), table_name='employment_indicators_agriculture')
    op.alter_column('employment_indicators_agriculture', 'year',
               existing_type=sa.SmallInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_index(op.f('ix_emissions_totals_year'), table_name='emissions_totals')
    op.alter_column('emissions_totals', 'year',
               existing_type=sa.SmallInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_index(op.f('ix_emissions_pre_post_production_year'), table_name='emissions_pre_post_production')
    op.alter_column('emissions_pre_post_production', 'value',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('emissions_pre_post_production', 'year',
               existing_type=sa.SmallInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_index(op.f('ix_emissions_livestock_year'), table_name='emissions_livestock')
    op.alter_column('emissions_livestock', 'year',
               existing_type=sa.SmallInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_index(op.f('ix_emissions_land_use_forests_year'), table_name='emissions_land_use_forests')
    op.alter_column('emissions_land_use_forests', 'year',
               existing_type=sa.SmallInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_index(op.f('ix_emissions_land_use_fires_year'), table_name='emissions_land_use_fires')
    op.alter_column('emissions_land_use_fires', 'year',
               existing_type=sa.SmallInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_index(op.f('ix_emissions_drained_organic_soils_year'), table_name='emissions_drained_organic_soils')
    op.alter_column('emissions_drained_organic_soils', 'year',
               existing_type=sa.SmallInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_index(op.f('ix_emissions_crops_year'), table_name='emissions_crops')
    op.alter_column('emissions_crops', 'year',
               existing_type=sa.SmallInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_index(op.f('ix_emissions_agriculture_energy_year'), table_name='emissions_agriculture_energy')
    op.alter_column('emissions_agriculture_energy', 'year',
               existing_type=sa.SmallInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.create_index(op.f('ix_elements_element_code'), 'elements', ['element_code'], unique=False)
    op.create_index(op.f('ix_donors_donor_code'), 'donors', ['donor_code'], unique=False)
    op.drop_index(op.f('ix_development_assistance_to_agriculture_year'), table_name='development_assistance_to_agriculture')
    op.alter_column('development_assistance_to_agriculture', 'year',
               existing_type=sa.SmallInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_index(op.f('ix_deflators_year'), table_name='deflators')
    op.alter_column('deflators', 'year',
               existing_type=sa.SmallInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.create_index(op.f('ix_currencies_iso_currency_code'), 'currencies', ['iso_currency_code'], unique=False)
    op.drop_index(op.f('ix_cost_affordability_healthy_diet_co_ahd_year'), table_name='cost_affordability_healthy_diet_co_ahd')
    op.alter_column('cost_affordability_healthy_diet_co_ahd', 'year',
               existing_type=sa.SmallInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_index(op.f('ix_consumer_price_indices_year'), table_name='consumer_price_indices')
    op.alter_column('consumer_price_indices', 'year',
               existing_type=sa.SmallInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_index(op.f('ix_commodity_balances_non_food_2013_old_methodology_year'), table_name='commodity_balances_non_food_2013_old_methodology')
    op.alter_column('commodity_balances_non_food_2013_old_methodology', 'year',
               existing_type=sa.SmallInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_index(op.f('ix_commodity_balances_non_food_2010_year'), table_name='commodity_balances_non_food_2010')
    op.alter_column('commodity_balances_non_food_2010', 'year',
               existing_type=sa.SmallInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_index(op.f('ix_commodity_balances_non_food_year'), table_name='commodity_balances_non_food')
    op.alter_column('commodity_balances_non_food', 'year',
               existing_type=sa.SmallInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_index(op.f('ix_climate_change_emissions_indicators_year'), table_name='climate_change_emissions_indicators')
    op.alter_column('climate_change_emissions_indicators', 'year',
               existing_type=sa.SmallInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_index(op.f('ix_asti_researchers_year'), table_name='asti_researchers')
    op.alter_column('asti_researchers', 'year',
               existing_type=sa.SmallInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_index(op.f('ix_asti_expenditures_year'), table_name='asti_expenditures')
    op.alter_column('asti_expenditures', 'year',
               existing_type=sa.SmallInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.create_index(op.f('ix_area_codes_area_code'), 'area_codes', ['area_code'], unique=False)
    # ### end Alembic commands ###
