"""init

Revision ID: f29bcc5c5edc
Revises: 
Create Date: 2025-05-30 20:00:42.402825

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f29bcc5c5edc'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('areas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('area_code', sa.Integer(), nullable=False),
    sa.Column('m49_code', sa.Integer(), nullable=False),
    sa.Column('area', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('consumer_price_indices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('area_code', sa.Integer(), nullable=False),
    sa.Column('area_code_m49', sa.Integer(), nullable=False),
    sa.Column('area', sa.String(), nullable=False),
    sa.Column('item_code', sa.Integer(), nullable=False),
    sa.Column('item', sa.String(), nullable=False),
    sa.Column('element_code', sa.Integer(), nullable=False),
    sa.Column('element', sa.String(), nullable=False),
    sa.Column('months_code', sa.Integer(), nullable=False),
    sa.Column('months', sa.String(), nullable=False),
    sa.Column('year_code', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('unit', sa.String(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('flag', sa.String(), nullable=False),
    sa.Column('note', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('consumer_price_indices_elements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('element_code', sa.Integer(), nullable=False),
    sa.Column('element', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('consumer_price_indices_flags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('flag', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('currencys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('iso_currency_code', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('emissions_land_use_fires',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('area_code', sa.Integer(), nullable=False),
    sa.Column('area_code_m49', sa.Integer(), nullable=False),
    sa.Column('area', sa.String(), nullable=False),
    sa.Column('item_code', sa.Integer(), nullable=False),
    sa.Column('item', sa.String(), nullable=False),
    sa.Column('element_code', sa.Integer(), nullable=False),
    sa.Column('element', sa.String(), nullable=False),
    sa.Column('year_code', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('source_code', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('unit', sa.String(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('flag', sa.String(), nullable=False),
    sa.Column('note', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('emissions_land_use_fires_flags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('flag', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('environment_bioenergy',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('area_code', sa.Integer(), nullable=False),
    sa.Column('area_code_m49', sa.Integer(), nullable=False),
    sa.Column('area', sa.String(), nullable=False),
    sa.Column('item_code', sa.Integer(), nullable=False),
    sa.Column('item', sa.String(), nullable=False),
    sa.Column('element_code', sa.Integer(), nullable=False),
    sa.Column('element', sa.String(), nullable=False),
    sa.Column('year_code', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('unit', sa.String(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('flag', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('environment_bioenergy_flags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('flag', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('environment_land_cover',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('area_code', sa.Integer(), nullable=False),
    sa.Column('area_code_m49', sa.Integer(), nullable=False),
    sa.Column('area', sa.String(), nullable=False),
    sa.Column('item_code', sa.Integer(), nullable=False),
    sa.Column('item', sa.String(), nullable=False),
    sa.Column('element_code', sa.Integer(), nullable=False),
    sa.Column('element', sa.String(), nullable=False),
    sa.Column('year_code', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('unit', sa.String(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('flag', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('environment_land_cover_flags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('flag', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('environment_pesticides',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('area_code', sa.Integer(), nullable=False),
    sa.Column('area_code_m49', sa.Integer(), nullable=False),
    sa.Column('area', sa.String(), nullable=False),
    sa.Column('item_code', sa.Integer(), nullable=False),
    sa.Column('item', sa.String(), nullable=False),
    sa.Column('element_code', sa.Integer(), nullable=False),
    sa.Column('element', sa.String(), nullable=False),
    sa.Column('year_code', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('unit', sa.String(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('flag', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('environment_pesticides_flags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('flag', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('exchange_rate',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('area_code', sa.Integer(), nullable=False),
    sa.Column('area_code_m49', sa.Integer(), nullable=False),
    sa.Column('area', sa.String(), nullable=False),
    sa.Column('element_code', sa.Integer(), nullable=False),
    sa.Column('element', sa.String(), nullable=False),
    sa.Column('iso_currency_code', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('year_code', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('months_code', sa.Integer(), nullable=False),
    sa.Column('months', sa.String(), nullable=False),
    sa.Column('unit', sa.String(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('flag', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('exchange_rate_elements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('element_code', sa.Integer(), nullable=False),
    sa.Column('element', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('exchange_rate_flags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('flag', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('forestry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('area_code', sa.Integer(), nullable=False),
    sa.Column('area_code_m49', sa.Integer(), nullable=False),
    sa.Column('area', sa.String(), nullable=False),
    sa.Column('item_code', sa.Integer(), nullable=False),
    sa.Column('item', sa.String(), nullable=False),
    sa.Column('element_code', sa.Integer(), nullable=False),
    sa.Column('element', sa.String(), nullable=False),
    sa.Column('year_code', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('unit', sa.String(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('flag', sa.String(), nullable=False),
    sa.Column('note', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('forestry_elements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('element_code', sa.Integer(), nullable=False),
    sa.Column('element', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('forestry_flags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('flag', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inputs_fertilizers_nutrient',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('area_code', sa.Integer(), nullable=False),
    sa.Column('area_code_m49', sa.Integer(), nullable=False),
    sa.Column('area', sa.String(), nullable=False),
    sa.Column('item_code', sa.Integer(), nullable=False),
    sa.Column('item', sa.String(), nullable=False),
    sa.Column('element_code', sa.Integer(), nullable=False),
    sa.Column('element', sa.String(), nullable=False),
    sa.Column('year_code', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('unit', sa.String(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('flag', sa.String(), nullable=False),
    sa.Column('note', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inputs_fertilizers_nutrient_flags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('flag', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('investment_capital_stock',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('area_code', sa.Integer(), nullable=False),
    sa.Column('area_code_m49', sa.Integer(), nullable=False),
    sa.Column('area', sa.String(), nullable=False),
    sa.Column('item_code', sa.Integer(), nullable=False),
    sa.Column('item', sa.String(), nullable=False),
    sa.Column('element_code', sa.Integer(), nullable=False),
    sa.Column('element', sa.String(), nullable=False),
    sa.Column('year_code', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('unit', sa.String(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('flag', sa.String(), nullable=False),
    sa.Column('note', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('investment_capital_stock_elements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('element_code', sa.Integer(), nullable=False),
    sa.Column('element', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('investment_capital_stock_flags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('flag', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('investment_country_investment_statistics_profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('area_code', sa.Integer(), nullable=False),
    sa.Column('area_code_m49', sa.Integer(), nullable=False),
    sa.Column('area', sa.String(), nullable=False),
    sa.Column('item_code', sa.Integer(), nullable=False),
    sa.Column('item', sa.String(), nullable=False),
    sa.Column('element_code', sa.Integer(), nullable=False),
    sa.Column('element', sa.String(), nullable=False),
    sa.Column('year_code', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('unit', sa.String(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('flag', sa.String(), nullable=False),
    sa.Column('note', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('investment_country_investment_statistics_profile_elements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('element_code', sa.Integer(), nullable=False),
    sa.Column('element', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('investment_country_investment_statistics_profile_flags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('flag', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_code', sa.Integer(), nullable=False),
    sa.Column('cpc_code', sa.Integer(), nullable=False),
    sa.Column('item', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('minimum_dietary_diversity_for_women_food_and_diet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('survey_code', sa.Integer(), nullable=False),
    sa.Column('survey', sa.String(), nullable=False),
    sa.Column('food_group_code', sa.Integer(), nullable=False),
    sa.Column('food_group', sa.String(), nullable=False),
    sa.Column('indicator_code', sa.Integer(), nullable=False),
    sa.Column('indicator', sa.String(), nullable=False),
    sa.Column('geographic_level_code', sa.Integer(), nullable=False),
    sa.Column('geographic_level', sa.String(), nullable=False),
    sa.Column('element_code', sa.Integer(), nullable=False),
    sa.Column('element', sa.String(), nullable=False),
    sa.Column('unit', sa.String(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('flag', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('minimum_dietary_diversity_for_women_food_and_diet_elements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('element_code', sa.Integer(), nullable=False),
    sa.Column('element', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('minimum_dietary_diversity_for_women_food_and_diet_flags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('flag', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('minimum_dietary_diversity_for_women_food_and_diet_indicators',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('indicator_code', sa.Integer(), nullable=False),
    sa.Column('indicator', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('minimum_dietary_diversity_for_women_food_and_diet_surveys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('survey_code', sa.Integer(), nullable=False),
    sa.Column('survey', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('population',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('area_code', sa.Integer(), nullable=False),
    sa.Column('area_code_m49', sa.Integer(), nullable=False),
    sa.Column('area', sa.String(), nullable=False),
    sa.Column('item_code', sa.Integer(), nullable=False),
    sa.Column('item', sa.String(), nullable=False),
    sa.Column('element_code', sa.Integer(), nullable=False),
    sa.Column('element', sa.String(), nullable=False),
    sa.Column('year_code', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('unit', sa.String(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('flag', sa.String(), nullable=False),
    sa.Column('note', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('population_elements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('element_code', sa.Integer(), nullable=False),
    sa.Column('element', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('population_flags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('flag', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('prices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('area_code', sa.Integer(), nullable=False),
    sa.Column('area_code_m49', sa.Integer(), nullable=False),
    sa.Column('area', sa.String(), nullable=False),
    sa.Column('item_code', sa.Integer(), nullable=False),
    sa.Column('item_code_cpc', sa.Integer(), nullable=False),
    sa.Column('item', sa.String(), nullable=False),
    sa.Column('element_code', sa.Integer(), nullable=False),
    sa.Column('element', sa.String(), nullable=False),
    sa.Column('year_code', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('months_code', sa.Integer(), nullable=False),
    sa.Column('months', sa.String(), nullable=False),
    sa.Column('unit', sa.String(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('flag', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('prices_elements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('element_code', sa.Integer(), nullable=False),
    sa.Column('element', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('prices_flags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('flag', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('prices_flags')
    op.drop_table('prices_elements')
    op.drop_table('prices')
    op.drop_table('population_flags')
    op.drop_table('population_elements')
    op.drop_table('population')
    op.drop_table('minimum_dietary_diversity_for_women_food_and_diet_surveys')
    op.drop_table('minimum_dietary_diversity_for_women_food_and_diet_indicators')
    op.drop_table('minimum_dietary_diversity_for_women_food_and_diet_flags')
    op.drop_table('minimum_dietary_diversity_for_women_food_and_diet_elements')
    op.drop_table('minimum_dietary_diversity_for_women_food_and_diet')
    op.drop_table('items')
    op.drop_table('investment_country_investment_statistics_profile_flags')
    op.drop_table('investment_country_investment_statistics_profile_elements')
    op.drop_table('investment_country_investment_statistics_profile')
    op.drop_table('investment_capital_stock_flags')
    op.drop_table('investment_capital_stock_elements')
    op.drop_table('investment_capital_stock')
    op.drop_table('inputs_fertilizers_nutrient_flags')
    op.drop_table('inputs_fertilizers_nutrient')
    op.drop_table('forestry_flags')
    op.drop_table('forestry_elements')
    op.drop_table('forestry')
    op.drop_table('exchange_rate_flags')
    op.drop_table('exchange_rate_elements')
    op.drop_table('exchange_rate')
    op.drop_table('environment_pesticides_flags')
    op.drop_table('environment_pesticides')
    op.drop_table('environment_land_cover_flags')
    op.drop_table('environment_land_cover')
    op.drop_table('environment_bioenergy_flags')
    op.drop_table('environment_bioenergy')
    op.drop_table('emissions_land_use_fires_flags')
    op.drop_table('emissions_land_use_fires')
    op.drop_table('currencys')
    op.drop_table('consumer_price_indices_flags')
    op.drop_table('consumer_price_indices_elements')
    op.drop_table('consumer_price_indices')
    op.drop_table('areas')
    # ### end Alembic commands ###
