food_balance_sheets = {
    "dataset": "food_balance_sheets",
    "total_elements": 21,
    "elements": [
        {"element_code": "5072", "element": "Stock Variation"},
        {"element_code": "511", "element": "Total Population - Both sexes"},
        {"element_code": "5123", "element": "Losses"},
        {"element_code": "5131", "element": "Processing"},
        {"element_code": "5142", "element": "Food"},
        {"element_code": "5154", "element": "Other uses (non-food)"},
        {"element_code": "5170", "element": "Residuals"},
        {"element_code": "5171", "element": "Tourist consumption"},
        {"element_code": "5301", "element": "Domestic supply quantity"},
        {"element_code": "5511", "element": "Production"},
        {"element_code": "5521", "element": "Feed"},
        {"element_code": "5527", "element": "Seed"},
        {"element_code": "5611", "element": "Import quantity"},
        {"element_code": "5911", "element": "Export quantity"},
        {"element_code": "645", "element": "Food supply quantity (kg/capita/yr)"},
        {"element_code": "661", "element": "Food supply (kcal)"},
        {"element_code": "664", "element": "Food supply (kcal/capita/day)"},
        {"element_code": "671", "element": "Protein supply quantity (t)"},
        {"element_code": "674", "element": "Protein supply quantity (g/capita/day)"},
        {"element_code": "681", "element": "Fat supply quantity (t)"},
        {"element_code": "684", "element": "Fat supply quantity (g/capita/day)"},
    ],
    "examples": [
        {
            "id": 1001,
            "area_code_id": 1414629581,
            "item_code_id": 1666801197,
            "element_code_id": 1969248714,
            "flag_id": 1890743110,
            "year_code": "2018",
            "year": 2018,
            "unit": "kcal/cap/d",
            "value": 2871.13,
            "note": "nan",
            "area_codes_area_code": "27",
            "area_codes_area": "Bulgaria",
            "area_codes_area_code_m49": "100",
            "item_codes_item_code": "2901",
            "item_codes_item": "Grand Total",
            "item_codes_item_code_cpc": "nan",
            "item_codes_item_code_fbs": "S2901",
            "item_codes_item_code_sdg": "nan",
            "elements_element_code": "664",
            "elements_element": "Food supply (kcal/capita/day)",
            "flags_flag": "E",
            "flags_description": "Estimated value",
        },
        {
            "id": 1065,
            "area_code_id": 1184194587,
            "item_code_id": 1666801197,
            "element_code_id": 1209268034,
            "flag_id": 1890743110,
            "year_code": "2022",
            "year": 2022,
            "unit": "t",
            "value": 23584.57,
            "note": "nan",
            "area_codes_area_code": "18",
            "area_codes_area": "Bhutan",
            "area_codes_area_code_m49": "064",
            "item_codes_item_code": "2901",
            "item_codes_item": "Grand Total",
            "item_codes_item_code_cpc": "nan",
            "item_codes_item_code_fbs": "S2901",
            "item_codes_item_code_sdg": "nan",
            "elements_element_code": "681",
            "elements_element": "Fat supply quantity (t)",
            "flags_flag": "E",
            "flags_description": "Estimated value",
        },
        {
            "id": 2100,
            "area_code_id": 1957700814,
            "item_code_id": 1555650506,
            "element_code_id": 1219548681,
            "flag_id": 1697338506,
            "year_code": "2022",
            "year": 2022,
            "unit": "1000 No",
            "value": 11228.82,
            "note": "nan",
            "area_codes_area_code": "56",
            "area_codes_area": "Dominican Republic",
            "area_codes_area_code_m49": "214",
            "item_codes_item_code": "2501",
            "item_codes_item": "Population",
            "item_codes_item_code_cpc": "nan",
            "item_codes_item_code_fbs": "S2501",
            "item_codes_item_code_sdg": "nan",
            "elements_element_code": "511",
            "elements_element": "Total Population - Both sexes",
            "flags_flag": "X",
            "flags_description": "Figure from international organizations",
        },
    ],
}
