food_security_data = {
    "dataset": "food_security_data",
    "total_elements": 12,
    "elements": [
        {"element_code": "6121", "element": "Value"},
        {"element_code": "61211", "element": "Confidence interval: Lower bound"},
        {"element_code": "61212", "element": "Confidence interval: Upper bound"},
        {"element_code": "6123", "element": "Value"},
        {"element_code": "6124", "element": "Value"},
        {"element_code": "6125", "element": "Value"},
        {"element_code": "6126", "element": "Value"},
        {"element_code": "6128", "element": "Value"},
        {"element_code": "6132", "element": "Value"},
        {"element_code": "61321", "element": "Confidence interval: Lower bound"},
        {"element_code": "61322", "element": "Confidence interval: Upper bound"},
        {"element_code": "6173", "element": "Value"},
    ],
    "examples": [
        {
            "id": 1,
            "area_code_id": 1959934226,
            "item_code_id": 986314429,
            "element_code_id": 1469653400,
            "flag_id": 1890743110,
            "year_code": "20002002",
            "year": "2000-2002",
            "unit": "%",
            "value": 87,
            "note": "nan",
            "area_codes_area_code": "2",
            "area_codes_area": "Afghanistan",
            "area_codes_area_code_m49": "004",
            "item_codes_item_code": "21010",
            "item_codes_item": "Average dietary energy supply adequacy (percent) (3-year average)",
            "item_codes_item_code_cpc": "nan",
            "item_codes_item_code_fbs": "nan",
            "item_codes_item_code_sdg": "nan",
            "elements_element_code": "6121",
            "elements_element": "Value",
            "flags_flag": "E",
            "flags_description": "Estimated value",
        },
        {
            "id": 24877,
            "area_code_id": 209833376,
            "item_code_id": 881746750,
            "element_code_id": 251584994,
            "flag_id": 1731318923,
            "year_code": "20172019",
            "year": "2017-2019",
            "unit": "%",
            "value": 57,
            "note": "Official estimate integrated with FAO data",
            "area_codes_area_code": "20",
            "area_codes_area": "Botswana",
            "area_codes_area_code_m49": "072",
            "item_codes_item_code": "210091",
            "item_codes_item": "Prevalence of moderate or severe food insecurity in the total population (percent) (3-year average)",
            "item_codes_item_code_cpc": "nan",
            "item_codes_item_code_fbs": "nan",
            "item_codes_item_code_sdg": "nan",
            "elements_element_code": "61212",
            "elements_element": "Confidence interval: Upper bound",
            "flags_flag": "A",
            "flags_description": "Official figure",
        },
    ],
    "items": [
        {
            "item_code": "210010",
            "item": "Number of people undernourished (million) (annual value)",
            "item_code_cpc": "nan",
            "item_code_fbs": "nan",
            "item_code_sdg": "nan",
        },
        {
            "item_code": "210011",
            "item": "Number of people undernourished (million) (3-year average)",
            "item_code_cpc": "nan",
            "item_code_fbs": "nan",
            "item_code_sdg": "nan",
        },
        {
            "item_code": "210040",
            "item": "Prevalence of undernourishment (percent) (annual value)",
            "item_code_cpc": "nan",
            "item_code_fbs": "nan",
            "item_code_sdg": "nan",
        },
        {
            "item_code": "210041",
            "item": "Prevalence of undernourishment (percent) (3-year average)",
            "item_code_cpc": "nan",
            "item_code_fbs": "nan",
            "item_code_sdg": "nan",
        },
        {
            "item_code": "210070",
            "item": "Number of severely food insecure people (million) (annual value)",
            "item_code_cpc": "nan",
            "item_code_fbs": "nan",
            "item_code_sdg": "nan",
        },
        {
            "item_code": "210070F",
            "item": "Number of severely food insecure female adults (million) (annual value)",
            "item_code_cpc": "nan",
            "item_code_fbs": "nan",
            "item_code_sdg": "nan",
        },
        {
            "item_code": "210070M",
            "item": "Number of severely food insecure male adults (million) (annual value)",
            "item_code_cpc": "nan",
            "item_code_fbs": "nan",
            "item_code_sdg": "nan",
        },
        {
            "item_code": "210071",
            "item": "Number of severely food insecure people (million) (3-year average)",
            "item_code_cpc": "nan",
            "item_code_fbs": "nan",
            "item_code_sdg": "nan",
        },
        {
            "item_code": "210071F",
            "item": "Number of severely food insecure female adults (million) (3-year average)",
            "item_code_cpc": "nan",
            "item_code_fbs": "nan",
            "item_code_sdg": "nan",
        },
        {
            "item_code": "210071M",
            "item": "Number of severely food insecure male adults (million) (3-year average)",
            "item_code_cpc": "nan",
            "item_code_fbs": "nan",
            "item_code_sdg": "nan",
        },
        {
            "item_code": "210080",
            "item": "Number of moderately or severely food insecure people (million) (annual value)",
            "item_code_cpc": "nan",
            "item_code_fbs": "nan",
            "item_code_sdg": "nan",
        },
        {
            "item_code": "210080F",
            "item": "Number of moderately or severely food insecure female adults (million) (annual value)",
            "item_code_cpc": "nan",
            "item_code_fbs": "nan",
            "item_code_sdg": "nan",
        },
        {
            "item_code": "210080M",
            "item": "Number of moderately or severely food insecure male adults (million) (annual value)",
            "item_code_cpc": "nan",
            "item_code_fbs": "nan",
            "item_code_sdg": "nan",
        },
        {
            "item_code": "210081",
            "item": "Number of moderately or severely food insecure people (million) (3-year average)",
            "item_code_cpc": "nan",
            "item_code_fbs": "nan",
            "item_code_sdg": "nan",
        },
        {
            "item_code": "210081F",
            "item": "Number of moderately or severely food insecure female adults (million) (3-year average)",
            "item_code_cpc": "nan",
            "item_code_fbs": "nan",
            "item_code_sdg": "nan",
        },
        {
            "item_code": "210081M",
            "item": "Number of moderately or severely food insecure male adults (million) (3-year average)",
            "item_code_cpc": "nan",
            "item_code_fbs": "nan",
            "item_code_sdg": "nan",
        },
        {
            "item_code": "210090",
            "item": "Prevalence of moderate or severe food insecurity in the total population (percent) (annual value)",
            "item_code_cpc": "nan",
            "item_code_fbs": "nan",
            "item_code_sdg": "nan",
        },
        {
            "item_code": "210090F",
            "item": "Prevalence of moderate or severe food insecurity in the female adult population (percent) (annual value)",
            "item_code_cpc": "nan",
            "item_code_fbs": "nan",
            "item_code_sdg": "nan",
        },
        {
            "item_code": "210090M",
            "item": "Prevalence of moderate or severe food insecurity in the male adult population (percent) (annual value)",
            "item_code_cpc": "nan",
            "item_code_fbs": "nan",
            "item_code_sdg": "nan",
        },
        {
            "item_code": "210090R",
            "item": "Prevalence of moderate or severe food insecurity in the rural adult population (percent) (annual value)",
            "item_code_cpc": "nan",
            "item_code_fbs": "nan",
            "item_code_sdg": "nan",
        },
        {
            "item_code": "210090TSUB",
            "item": "Prevalence of moderate or severe food insecurity in the town and semi-dense area adult population (percent) (annual value)",
            "item_code_cpc": "nan",
            "item_code_fbs": "nan",
            "item_code_sdg": "nan",
        },
        {
            "item_code": "210090U",
            "item": "Prevalence of moderate or severe food insecurity in the urban adult population (percent) (annual value)",
            "item_code_cpc": "nan",
            "item_code_fbs": "nan",
            "item_code_sdg": "nan",
        },
        {
            "item_code": "210091",
            "item": "Prevalence of moderate or severe food insecurity in the total population (percent) (3-year average)",
            "item_code_cpc": "nan",
            "item_code_fbs": "nan",
            "item_code_sdg": "nan",
        },
        {
            "item_code": "210091F",
            "item": "Prevalence of moderate or severe food insecurity in the female adult population (percent) (3-year average)",
            "item_code_cpc": "nan",
            "item_code_fbs": "nan",
            "item_code_sdg": "nan",
        },
        {
            "item_code": "210091M",
            "item": "Prevalence of moderate or severe food insecurity in the male adult population (percent) (3-year average)",
            "item_code_cpc": "nan",
            "item_code_fbs": "nan",
            "item_code_sdg": "nan",
        },
        {
            "item_code": "21010",
            "item": "Average dietary energy supply adequacy (percent) (3-year average)",
            "item_code_cpc": "nan",
            "item_code_fbs": "nan",
            "item_code_sdg": "nan",
        },
        {
            "item_code": "21012",
            "item": "Share of dietary energy supply derived from cereals, roots and tubers (percent) (3-year average)",
            "item_code_cpc": "nan",
            "item_code_fbs": "nan",
            "item_code_sdg": "nan",
        },
        {
            "item_code": "21013",
            "item": "Average protein supply (g/cap/day) (3-year average)",
            "item_code_cpc": "nan",
            "item_code_fbs": "nan",
            "item_code_sdg": "nan",
        },
        {
            "item_code": "21014",
            "item": "Average supply of protein of animal origin (g/cap/day) (3-year average)",
            "item_code_cpc": "nan",
            "item_code_fbs": "nan",
            "item_code_sdg": "nan",
        },
        {
            "item_code": "21016",
            "item": "Rail lines density (total route in km per 100 square km of land area)",
            "item_code_cpc": "nan",
            "item_code_fbs": "nan",
            "item_code_sdg": "nan",
        },
        {
            "item_code": "21025",
            "item": "Percentage of children under 5 years of age who are stunted (modelled estimates) (percent)",
            "item_code_cpc": "nan",
            "item_code_fbs": "nan",
            "item_code_sdg": "nan",
        },
        {
            "item_code": "210250",
            "item": "Number of children under 5 years of age who are stunted (modeled estimates) (million)",
            "item_code_cpc": "nan",
            "item_code_fbs": "nan",
            "item_code_sdg": "nan",
        },
        {
            "item_code": "21026",
            "item": "Percentage of children under 5 years affected by wasting (percent)",
            "item_code_cpc": "nan",
            "item_code_fbs": "nan",
            "item_code_sdg": "nan",
        },
        {
            "item_code": "210260",
            "item": "Number of children under 5 years affected by wasting (million)",
            "item_code_cpc": "nan",
            "item_code_fbs": "nan",
            "item_code_sdg": "nan",
        },
        {
            "item_code": "21031",
            "item": "Per capita food supply variability (kcal/cap/day)",
            "item_code_cpc": "nan",
            "item_code_fbs": "nan",
            "item_code_sdg": "nan",
        },
        {
            "item_code": "21032",
            "item": "Political stability and absence of violence/terrorism (index)",
            "item_code_cpc": "nan",
            "item_code_fbs": "nan",
            "item_code_sdg": "nan",
        },
        {
            "item_code": "21033",
            "item": "Value of food imports in total merchandise exports (percent) (3-year average)",
            "item_code_cpc": "nan",
            "item_code_fbs": "nan",
            "item_code_sdg": "nan",
        },
        {
            "item_code": "21034",
            "item": "Percent of arable land equipped for irrigation (percent) (3-year average)",
            "item_code_cpc": "nan",
            "item_code_fbs": "nan",
            "item_code_sdg": "nan",
        },
        {
            "item_code": "21035",
            "item": "Cereal import dependency ratio (percent) (3-year average)",
            "item_code_cpc": "nan",
            "item_code_fbs": "nan",
            "item_code_sdg": "nan",
        },
        {
            "item_code": "210400",
            "item": "Prevalence of severe food insecurity in the total population (percent) (annual value)",
            "item_code_cpc": "nan",
            "item_code_fbs": "nan",
            "item_code_sdg": "nan",
        },
        {
            "item_code": "210400F",
            "item": "Prevalence of severe food insecurity in the female adult population (percent) (annual value)",
            "item_code_cpc": "nan",
            "item_code_fbs": "nan",
            "item_code_sdg": "nan",
        },
        {
            "item_code": "210400M",
            "item": "Prevalence of severe food insecurity in the male adult population (percent) (annual value)",
            "item_code_cpc": "nan",
            "item_code_fbs": "nan",
            "item_code_sdg": "nan",
        },
        {
            "item_code": "210400R",
            "item": "Prevalence of severe food insecurity in the rural adult population (percent) (annual value)",
            "item_code_cpc": "nan",
            "item_code_fbs": "nan",
            "item_code_sdg": "nan",
        },
        {
            "item_code": "210400TSUB",
            "item": "Prevalence of severe food insecurity in the town and semi-dense area adult population (percent) (annual value)",
            "item_code_cpc": "nan",
            "item_code_fbs": "nan",
            "item_code_sdg": "nan",
        },
        {
            "item_code": "210400U",
            "item": "Prevalence of severe food insecurity in the urban adult population (percent) (annual value)",
            "item_code_cpc": "nan",
            "item_code_fbs": "nan",
            "item_code_sdg": "nan",
        },
        {
            "item_code": "210401",
            "item": "Prevalence of severe food insecurity in the total population (percent) (3-year average)",
            "item_code_cpc": "nan",
            "item_code_fbs": "nan",
            "item_code_sdg": "nan",
        },
        {
            "item_code": "210401F",
            "item": "Prevalence of severe food insecurity in the female adult population (percent) (3-year average)",
            "item_code_cpc": "nan",
            "item_code_fbs": "nan",
            "item_code_sdg": "nan",
        },
        {
            "item_code": "210401M",
            "item": "Prevalence of severe food insecurity in the male adult population (percent) (3-year average)",
            "item_code_cpc": "nan",
            "item_code_fbs": "nan",
            "item_code_sdg": "nan",
        },
        {
            "item_code": "21041",
            "item": "Percentage of children under 5 years of age who are overweight (modelled estimates) (percent)",
            "item_code_cpc": "nan",
            "item_code_fbs": "nan",
            "item_code_sdg": "nan",
        },
        {
            "item_code": "210410",
            "item": "Number of children under 5 years of age who are overweight (modeled estimates) (million)",
            "item_code_cpc": "nan",
            "item_code_fbs": "nan",
            "item_code_sdg": "nan",
        },
        {
            "item_code": "21042",
            "item": "Prevalence of obesity in the adult population (18 years and older) (percent)",
            "item_code_cpc": "nan",
            "item_code_fbs": "nan",
            "item_code_sdg": "nan",
        },
        {
            "item_code": "210420",
            "item": "Number of obese adults (18 years and older) (million)",
            "item_code_cpc": "nan",
            "item_code_fbs": "nan",
            "item_code_sdg": "nan",
        },
        {
            "item_code": "21043",
            "item": "Prevalence of anemia among women of reproductive age (15-49 years) (percent)",
            "item_code_cpc": "nan",
            "item_code_fbs": "nan",
            "item_code_sdg": "nan",
        },
        {
            "item_code": "210430",
            "item": "Number of women of reproductive age (15-49 years) affected by anemia (million)",
            "item_code_cpc": "nan",
            "item_code_fbs": "nan",
            "item_code_sdg": "nan",
        },
        {
            "item_code": "21044",
            "item": "Prevalence of exclusive breastfeeding among infants 0-5 months of age (percent)",
            "item_code_cpc": "nan",
            "item_code_fbs": "nan",
            "item_code_sdg": "nan",
        },
        {
            "item_code": "21045",
            "item": "Percentage of population using safely managed drinking water services (percent)",
            "item_code_cpc": "nan",
            "item_code_fbs": "nan",
            "item_code_sdg": "nan",
        },
        {
            "item_code": "21046",
            "item": "Percentage of population using safely managed sanitation services (percent)",
            "item_code_cpc": "nan",
            "item_code_fbs": "nan",
            "item_code_sdg": "nan",
        },
        {
            "item_code": "21047",
            "item": "Percentage of population using at least basic drinking water services (percent)",
            "item_code_cpc": "nan",
            "item_code_fbs": "nan",
            "item_code_sdg": "nan",
        },
        {
            "item_code": "21048",
            "item": "Percentage of population using at least basic sanitation services (percent)",
            "item_code_cpc": "nan",
            "item_code_fbs": "nan",
            "item_code_sdg": "nan",
        },
        {
            "item_code": "21049",
            "item": "Prevalence of low birthweight (percent)",
            "item_code_cpc": "nan",
            "item_code_fbs": "nan",
            "item_code_sdg": "nan",
        },
        {
            "item_code": "210490",
            "item": "Number of newborns with low birthweight (million)",
            "item_code_cpc": "nan",
            "item_code_fbs": "nan",
            "item_code_sdg": "nan",
        },
        {
            "item_code": "21056",
            "item": "Minimum dietary energy requirement  (kcal/cap/day)",
            "item_code_cpc": "nan",
            "item_code_fbs": "nan",
            "item_code_sdg": "nan",
        },
        {
            "item_code": "21057",
            "item": "Average dietary energy requirement (kcal/cap/day)",
            "item_code_cpc": "nan",
            "item_code_fbs": "nan",
            "item_code_sdg": "nan",
        },
        {
            "item_code": "21058",
            "item": "Coefficient of variation of habitual caloric consumption distribution (real number)",
            "item_code_cpc": "nan",
            "item_code_fbs": "nan",
            "item_code_sdg": "nan",
        },
        {
            "item_code": "21059",
            "item": "Incidence of caloric losses at retail distribution level (percent)",
            "item_code_cpc": "nan",
            "item_code_fbs": "nan",
            "item_code_sdg": "nan",
        },
        {
            "item_code": "21061",
            "item": "Average fat supply (g/cap/day) (3-year average)",
            "item_code_cpc": "nan",
            "item_code_fbs": "nan",
            "item_code_sdg": "nan",
        },
        {
            "item_code": "22000",
            "item": "Dietary energy supply used in the estimation of the prevalence of undernourishment (kcal/cap/day) (3-year average)",
            "item_code_cpc": "nan",
            "item_code_fbs": "nan",
            "item_code_sdg": "nan",
        },
        {
            "item_code": "220001",
            "item": "Dietary energy supply used in the estimation of the prevalence of undernourishment (kcal/cap/day)",
            "item_code_cpc": "nan",
            "item_code_fbs": "nan",
            "item_code_sdg": "nan",
        },
        {
            "item_code": "22013",
            "item": "Gross domestic product per capita, PPP, (constant 2017 international $)",
            "item_code_cpc": "nan",
            "item_code_fbs": "nan",
            "item_code_sdg": "nan",
        },
    ],
}
